#!/bin/bash
LOCAL_PICTURE_DIR=$1
REMOTE_PICTURE_DIR=$2
CREDENTIALS_FILE=$3

python take_picture.py $LOCAL_PICTURE_DIR
python upload_picture.py $LOCAL_PICTURE_DIR $REMOTE_PICTURE_DIR $CREDENTIALS_FILE
